[package]
name = "carpenter"
version = "0.1.0"
edition = "2021"

[dependencies]
mio = { version = "=0.8", features = ["net", "os-poll", "os-ext"] }
rustls = { version = "=0.20.7", features = ["dangerous_configuration"] }
rustls-pemfile = "=0.2.1"
webpki-roots = "=0.21.1"
webpki = "=0.22.0"
wd_log = "=0.1"
toml = "=0.5.8"
domain = "=0.6.1"
base64 = "=0.13.1"
rcgen = { version = "=0.14.1", features = ["pem", "x509-parser"] }
httparse = "=1.10.1"
url = "=2.4.1"
sha2 = "=0.10"
pem = "=3.0.5"
x509-parser = "=0.17.0"
time-core = "=0.1.2"
zeroize = "=1.8.1"

[[bin]]
name = "carpenter"
path = "crate/main.rs"
